package org.grakovne.sideload.kindle.platform

enum class PlatformError {
    ONLY_64_BIT_PLATFORM_ARE_SUPPORTED_EXCEPT_LINUX,
    WINDOWS_PLATFORM_IS_NOT_SUPPORTED,
    UNABLE_TO_DEFINE_PLATFORM,
    UNABLE_TO_DEFINE_LINUX_PLATFORM
}