spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/kindle_sideload
    username: kindle_sideload
    password: kindle_sideload
    driverClassName: org.postgresql.Driver

telegram:
  token: 6586219940:AAGHD_H2nsepHAvtrSTg5-V0lZQFAJ_umIQ
  level: DEBUG

ads:
  blockDelimiter: "\n\n_____\n\n"
  creatives:

user:
  converter:
    configuration:
      path: "user_configurations"
      file-name: "configuration.zip"
      max-size: 20000000
  environment:
    temporaryFolder: "user_environments"

converter:
  binary:
    releasesUrl: "https://api.github.com/repos/rupor-github/fb2converter/releases/latest"
    extension: ".zip"
    binaryPersistencePath: "fb2_converter"
    converterFileName: "fb2c"
    shell: "/bin/bash"
    shellArgs: "-c"
    configurationExtension: ".toml"
  sourceFileExtensions: "fb2"

environment:
  temporaryFolder: "temporary_user_environments"