spring:
  mail:
    from: "sideload@grakovne.org"
    subject: "Your Subject Here"
    text: "Your Text Here"
    host: "smtp.mail.me.com"
    port: "587"
    username: "grakovne@gmail.com"
    password: "gael-seus-akal-habk"
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/kindle_sideload
    username: kindle_sideload
    password: kindle_sideload
    driverClassName: org.postgresql.Driver

telegram:
  token: 6774391168:AAHvA34GxLg6g5x4joR85fax_rZdnuUM8dY
  level: WARN
  deduplicateMessages: true

ads:
  blockDelimiter: "\n\n_____\n\n"
  creatives:

user:
  converter:
    configuration:
      path: "user_configurations"
      file-name: "configuration.zip"
  environment:
    temporaryFolder: "user_environments"

file:
  upload:
    max-size: 20000000

converter:
  source:
    releasesUrl: "https://api.github.com/repos/rupor-github/fb2converter/releases/latest"
  binary:
    binaryPersistencePath: "fb2_converter"
    converterFileName: "fb2c"
    shell: "/bin/bash"
    shellArgs: "-c"
    configurationExtensions: [ "toml", "yaml", "json" ]
    converterParameters: "--stk"
  sourceFileExtensions: [ "fb2", "fb2.zip" ]

environment:
  temporaryFolder: "temporary_user_environments"
  outputFileExtensions: ["epub", "azw3"]
  ttlInSeconds: 86400

logging:
  level:
    root: INFO
    org.grakovne: DEBUG
    org.hibernate: ERROR