package org.grakovne.sideload.kindle.user.configuration.domain

import org.grakovne.sideload.kindle.events.core.EventProcessingError
import org.grakovne.sideload.kindle.user.configuration.validation.ConfigurationValidationError

interface UserConverterConfigurationError : EventProcessingError

data object ConfigurationNotFoundError : UserConverterConfigurationError
data object UnableUpdateConfigurationError : UserConverterConfigurationError
object InternalError : UserConverterConfigurationError
object FileAbsentError : UserConverterConfigurationError
object FileIsTooLargeError : UserConverterConfigurationError
data class ValidationError(val code: ConfigurationValidationError) : UserConverterConfigurationError