package org.grakovne.sideload.kindle.telegram.domain.error

data object TargetUserDisappear: NewEventProcessingError
data object UnableSendResponse: NewEventProcessingError
data object UndescribedError: NewEventProcessingError
data object LocalizationError: NewEventProcessingError